'use strict';

require('dotenv').config();
const WebSocket = require('ws');
const logger = require('./logger');
const { buildAgentSystemPrompt } = require('./agent-configs');

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const REALTIME_URL = 'wss://api.openai.com/v1/realtime?model=gpt-4o-realtime-preview';

/**
 * OpenAI Realtime voice agent for outbound Twilio calls.
 *
 * Audio pipeline (zero transcoding):
 *   Twilio ulaw 8kHz base64 → input_audio_buffer.append → OpenAI
 *   OpenAI response.audio.delta base64 → direct to Twilio
 *
 * For sourcing_negotiation calls: userContext = pre-compiled call playbook string
 * (generated by planner.js before call starts). Used directly as session.instructions.
 *
 * For other agent types: system prompt built from agent-configs.js as before.
 */
class OutboundAgent {
  constructor({
    taskId, description, phoneNumber,
    agentType = 'generic', agentMode = null, userContext = null,
    onAudioOut, onMarkComplete, onAgentText, onUserText,
  }) {
    this.taskId         = taskId;
    this.description    = description;
    this.phoneNumber    = phoneNumber;
    this.agentType      = agentType;
    this.agentMode      = agentMode;
    this.userContext    = userContext;
    this.onAudioOut     = onAudioOut;
    this.onMarkComplete = onMarkComplete;
    this.onAgentText    = onAgentText;
    this.onUserText     = onUserText;

    this.ws             = null;
    this.ready          = false;
    this._disconnecting = false;
    this._chunkCount    = 0;
    this._pendingToolCallId = null;
  }

  connect() {
    logger.info({ taskId: this.taskId, phoneNumber: this.phoneNumber }, 'openai realtime connecting');

    this.ws = new WebSocket(REALTIME_URL, {
      headers: {
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
        'OpenAI-Beta': 'realtime=v1',
      },
    });

    return new Promise((resolve, reject) => {
      this.ws.once('open', () => {
        logger.info({ taskId: this.taskId }, 'openai realtime websocket open');
        this._initSession();
        resolve();
      });

      this.ws.once('error', (err) => {
        logger.error({ taskId: this.taskId, err: err.message }, 'openai realtime error (connect)');
        reject(err);
      });

      this.ws.on('message', (data) => {
        try {
          const msg = JSON.parse(data.toString());
          this._handleEvent(msg);
        } catch {
          logger.warn({ raw: data.toString().slice(0, 120) }, 'openai realtime non-json message');
        }
      });

      this.ws.on('error', (err) => {
        logger.error({ taskId: this.taskId, err: err.message }, 'openai realtime websocket error');
      });

      this.ws.on('close', (code, reason) => {
        this.ready = false;
        const reasonStr = reason?.toString() || '(none)';
        logger.info({ taskId: this.taskId, code, reason: reasonStr }, 'openai realtime websocket closed');
        if (code !== 1000 && code !== 1001 && !this._disconnecting) {
          this.onMarkComplete?.(
            `Call interrupted: OpenAI Realtime connection lost (code=${code} reason=${reasonStr})`,
            'failed'
          );
        }
      });
    });
  }

  _buildSystemPrompt() {
    // sourcing_negotiation: userContext IS the pre-compiled playbook from planner.js
    if (this.agentType === 'sourcing_negotiation' && this.userContext) {
      return this.userContext;
    }
    // All other agent types: use agent-configs.js
    return buildAgentSystemPrompt({
      agentType:   this.agentType,
      agentMode:   this.agentMode,
      description: this.description,
      phoneNumber: this.phoneNumber,
      userContext: this.userContext,
    });
  }

  _initSession() {
    const instructions = this._buildSystemPrompt();

    const sessionUpdate = {
      type: 'session.update',
      session: {
        modalities: ['audio', 'text'],
        instructions,
        voice: 'alloy',
        input_audio_format: 'g711_ulaw',
        output_audio_format: 'g711_ulaw',
        input_audio_transcription: { model: 'whisper-1', language: 'en' },
        turn_detection: {
          type: 'server_vad',
          threshold: 0.7,
          prefix_padding_ms: 300,
          silence_duration_ms: 700,
        },
        tools: [
          {
            type: 'function',
            name: 'mark_complete',
            description: 'Call this when the task is done or the call should end. Pass a brief summary of the outcome.',
            parameters: {
              type: 'object',
              properties: {
                result: { type: 'string', description: 'Summary of what was accomplished or why the call ended.' },
              },
              required: ['result'],
            },
          },
        ],
        tool_choice: 'auto',
        temperature: 0.8,
        max_response_output_tokens: 100,
      },
    };

    this.ws.send(JSON.stringify(sessionUpdate));
    logger.info({ taskId: this.taskId, agentType: this.agentType }, 'openai realtime session.update sent');
  }

  _handleEvent(msg) {
    switch (msg.type) {
      case 'session.created':
        this.ready = true;
        logger.info({ taskId: this.taskId }, 'openai session ready');
        break;

      case 'session.updated':
        logger.debug({ taskId: this.taskId }, 'openai session updated');
        break;

      case 'response.audio.delta':
        // base64 g711_ulaw — send directly to Twilio (zero transcoding)
        if (msg.delta) {
          this.onAudioOut?.(msg.delta);
        }
        break;

      case 'response.audio.done':
        logger.debug({ taskId: this.taskId }, 'openai audio response done');
        break;

      case 'response.audio_transcript.done':
        if (msg.transcript) {
          logger.info({ taskId: this.taskId, text: msg.transcript }, 'agent said');
          this.onAgentText?.(msg.transcript);
        }
        break;

      case 'conversation.item.input_audio_transcription.completed':
        if (msg.transcript) {
          logger.info({ taskId: this.taskId, text: msg.transcript }, 'user said');
          this.onUserText?.(msg.transcript);
        }
        break;

      case 'response.function_call_arguments.done':
        this._handleToolCall(msg).catch(err =>
          logger.error({ taskId: this.taskId, err: err.message }, 'tool call handler failed')
        );
        break;

      case 'response.done':
        logger.debug({ taskId: this.taskId }, 'openai response done');
        break;

      case 'input_audio_buffer.speech_started':
        logger.debug({ taskId: this.taskId }, 'user speech started');
        break;

      case 'input_audio_buffer.speech_stopped':
        logger.debug({ taskId: this.taskId }, 'user speech stopped');
        break;

      case 'error':
        logger.error({ taskId: this.taskId, error: msg.error }, 'openai realtime error event');
        if (msg.error?.type === 'server_error') {
          this.onMarkComplete?.(`Call failed: OpenAI error — ${msg.error.message}`, 'failed');
        }
        break;

      default:
        logger.debug({ taskId: this.taskId, type: msg.type }, 'openai realtime event');
    }
  }

  async _handleToolCall(msg) {
    const { name, call_id, arguments: argsStr } = msg;
    logger.info({ taskId: this.taskId, name, call_id }, 'openai tool call');

    let args = {};
    try { args = JSON.parse(argsStr || '{}'); } catch { /* ignore */ }

    if (name === 'mark_complete') {
      const result = args.result ?? 'Call completed.';
      this.onMarkComplete?.(result);

      // Send tool result back so GPT-4o doesn't hang
      this._sendToolResult(call_id, 'Acknowledged. Ending call.');
      return;
    }

    logger.warn({ taskId: this.taskId, name }, 'unknown tool call');
    this._sendToolResult(call_id, 'Tool not available.');
  }

  _sendToolResult(callId, output) {
    if (this.ws?.readyState !== WebSocket.OPEN) return;
    this.ws.send(JSON.stringify({
      type: 'conversation.item.create',
      item: {
        type: 'function_call_output',
        call_id: callId,
        output,
      },
    }));
    this.ws.send(JSON.stringify({ type: 'response.create' }));
  }

  /**
   * Send Twilio ulaw 8kHz base64 payload to OpenAI Realtime.
   * g711_ulaw is OpenAI's native format — zero transcoding.
   */
  sendUlawChunk(base64Payload) {
    if (!this.ready || !this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    this._chunkCount++;
    if (this._chunkCount % 50 === 0) {
      logger.info({ taskId: this.taskId, chunks: this._chunkCount }, 'audio chunks sent to openai');
    }
    this.ws.send(JSON.stringify({
      type: 'input_audio_buffer.append',
      audio: base64Payload,
    }));
  }

  /**
   * Inject guidance mid-call via a system conversation item.
   * v1: no-op placeholder — pre-call playbook handles all strategy.
   * v2: inject as system message if needed.
   */
  injectPlannerInstruction(instruction) {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    this.ws.send(JSON.stringify({
      type: 'conversation.item.create',
      item: {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: `[ADVISOR NOTE]: ${instruction}` }],
      },
    }));
    logger.info({ taskId: this.taskId }, 'advisor note injected into openai session');
  }

  disconnect() {
    this.ready = false;
    this._disconnecting = true;
    this.ws?.close();
    logger.info({ taskId: this.taskId }, 'openai realtime agent disconnected');
  }
}

module.exports = OutboundAgent;
